version: '3.7'

services:

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'P@ssw0rd'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - mysql:/var/lib/mysql

  rails:
    build: ./
    command: bash -c
      "rails db:create && 
      rails db:migrate &&
      bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - '3000:3000'
    volumes:
      - .:/docker/app
    depends_on:
      - db
      - kafka
      - redis
      - elasticsearch

  karafka:
    build: ./
    command: "bundle exec karafka server"
    depends_on:
      - rails
  
  redis:
    image: redis
    command: redis-server
    restart: always
    ports:
      - '6379:6379'

  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.2
    hostname: zookeeper
    ports:
      - '2181:2181'
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_SERVERS: zookeeper:2888:3888

  kafka:
    image: confluentinc/cp-kafka:7.3.2
    hostname: kafka
    ports:
      - '9092:9092'
      - '29092:29092'
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_BROKER_ID: 1
      KAFKA_LOG4J_LOGGERS: 'kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_AUTHORIZER_CLASS_NAME: kafka.security.authorizer.AclAuthorizer
      KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: 'true'
    depends_on:
      - zookeeper

  kowl:
    image: quay.io/cloudhut/kowl:v1.5.0
    restart: unless-stopped
    environment:
      KAFKA_BROKERS: 'kafka:9092'
    ports:
      - '7000:8080'
    depends_on:
      - kafka

  elasticsearch:
   image: docker.elastic.co/elasticsearch/elasticsearch:7.6.0
   volumes:
     - elasticsearch:/usr/share/elasticsearch/data
   ports:
     - '9200:9200'
   environment:
     - discovery.type=single-node
     - xpack.security.enabled=true
     - ELASTIC_PASSWORD=P@ssw0rd

volumes:
  mysql:
  elasticsearch: